apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-analyzer-ingress
  namespace: youtube-analyzer
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: <FRONTEND_PUBLIC_IP_OR_DOMAIN>
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80
    - host: <BACKEND_PUBLIC_IP_OR_DOMAIN>
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: backend-service
              port:
                number: 8000
  tls:
    - hosts:
        - <FRONTEND_PUBLIC_IP_OR_DOMAIN>
        - <BACKEND_PUBLIC_IP_OR_DOMAIN>
      secretName: youtube-analyzer-tls